PNGfromXCF+=	sphinxes-route.png
PNGfromXCF+=	sphinx-route.png
PNGfromXCF+=	spores-squads.png


.PHONY: all
all: ${PNGfromXCF}


.PHONY: clean
clean:
	${RM} ${PNGfromXCF}


.PHONY: distclean
distclean:
	true


INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/doc.mk
